# Generated by Django 5.2 on 2026-03-12 10:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('resource', 'Resource'), ('product', 'Product'), ('blogpost', 'Blogpost')], db_index=True, max_length=20)),
                ('target_id', models.PositiveIntegerField(db_index=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('star_1', models.PositiveIntegerField(default=0)),
                ('star_2', models.PositiveIntegerField(default=0)),
                ('star_3', models.PositiveIntegerField(default=0)),
                ('star_4', models.PositiveIntegerField(default=0)),
                ('star_5', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Engagement Summaries',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('resource', 'Resource'), ('product', 'Product'), ('blogpost', 'Blogpost')], db_index=True, max_length=20)),
                ('target_id', models.PositiveIntegerField(db_index=True)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('resource', 'Resource'), ('product', 'Product'), ('blogpost', 'Blogpost')], db_index=True, max_length=20)),
                ('target_id', models.PositiveIntegerField(db_index=True)),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='engagement.comment')),
            ],
        ),
    ]
