# Generated by Django 5.2 on 2026-03-05 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('shipping', 'Shipping Address'), ('billing', 'Billing Address')], default='shipping', max_length=10, verbose_name='Address Type')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Recipient Name')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state_province_county', models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Province/County')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('country', models.CharField(default='Nigeria', max_length=100, verbose_name='Country')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number')),
                ('is_default_shipping', models.BooleanField(default=False, verbose_name='Default Shipping Address')),
                ('is_default_billing', models.BooleanField(default=False, verbose_name='Default Billing Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['-is_default_shipping', '-is_default_billing', '-updated_at'],
            },
        ),
    ]
