# Generated by Django 5.2 on 2026-03-23 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('label', models.CharField(blank=True, help_text='Optional friendly name, e.g. "My maths worksheets".', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Search',
                'verbose_name_plural': 'Saved Searches',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'query')},
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=200)),
                ('result_count', models.PositiveSmallIntegerField(default=0)),
                ('resource_count', models.PositiveSmallIntegerField(default=0)),
                ('product_count', models.PositiveSmallIntegerField(default=0)),
                ('post_count', models.PositiveSmallIntegerField(default=0)),
                ('was_cached', models.BooleanField(default=False)),
                ('searched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null for anonymous searches.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Log',
                'verbose_name_plural': 'Search Logs',
                'ordering': ['-searched_at'],
                'indexes': [models.Index(fields=['query', 'searched_at'], name='searchlog_query_time_idx')],
            },
        ),
    ]
