# Generated by Django 5.2 on 2026-03-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_search_vector_product_product_search_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Check this box to showcase this product on the homepage.'),
        ),
    ]
