# Generated by Django 5.2 on 2026-03-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', help_text='3-letter ISO code', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('gateway', models.CharField(choices=[('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='flutterwave', max_length=20)),
                ('gateway_reference', models.CharField(help_text='e.g., your generated tx_ref', max_length=100, unique=True)),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='e.g., the ID Flutterwave returns', max_length=100, null=True)),
                ('purpose', models.CharField(choices=[('subscription', 'Subscription'), ('order', 'Product Order')], db_index=True, max_length=20)),
                ('purpose_id', models.PositiveIntegerField(db_index=True, help_text='ID of the Subscription or Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20)),
                ('payload', models.TextField(help_text='Raw JSON body from the provider')),
                ('headers', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='unprocessed', help_text='unprocessed, processed, or error', max_length=20)),
                ('processing_notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
