# Generated by Django 5.2 on 2026-03-16 12:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('html_content', models.TextField(help_text='Full HTML content of the newsletter.', verbose_name='HTML Content')),
                ('plain_text_content', models.TextField(blank=True, help_text='Optional. If blank, auto-stripped from HTML when sending.', verbose_name='Plain Text Content')),
                ('scheduled_send_time', models.DateTimeField(blank=True, help_text='Celery Beat will dispatch the send task at or after this time.', null=True, verbose_name='Scheduled Send Time')),
                ('is_sent', models.BooleanField(default=False, editable=False, verbose_name='Is Sent')),
                ('sent_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Sent At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Newsletter Issue',
                'verbose_name_plural': 'Newsletter Issues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to unsubscribe without deleting the record.', verbose_name='Is Active')),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Used to generate safe one-click unsubscribe links.', unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Subscribed At')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Unsubscribed At')),
                ('user', models.ForeignKey(blank=True, help_text='Set automatically when a registered user subscribes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Associated User')),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
