# Generated by Django 5.2 on 2026-03-12 10:47

import django.contrib.postgres.search
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main headline for the slide.', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Subtext below the headline.', max_length=300)),
                ('image', models.ImageField(help_text='High-resolution background image.', upload_to='hero_slides/')),
                ('link', models.CharField(default='/library', help_text='Where the button should go (e.g., /library or /products/1).', max_length=200)),
                ('btn_text', models.CharField(default='Explore Now', help_text='Text inside the button.', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this slide from the homepage.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='resources.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('worksheet', 'Worksheet'), ('lesson_plan', 'Lesson Plan'), ('presentation', 'Presentation'), ('interactive', 'Interactive Media')], default='worksheet', max_length=50)),
                ('access_level', models.CharField(choices=[('free', 'Free (Login Required)'), ('subscriber', 'Subscriber Only')], default='subscriber', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('file', models.FileField(upload_to='resources/files/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='resources/covers/originals/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Generated automatically by background task.', null=True, upload_to='resources/covers/thumbnails/')),
                ('is_featured', models.BooleanField(default=False, help_text='Check this box to showcase this resource on the homepage.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='resources.category')),
            ],
        ),
        migrations.CreateModel(
            name='SavedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='resources.resource')),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
    ]
