# Generated by Django 5.2 on 2026-03-12 10:47

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedresource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_resource_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='resource_search_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='savedresource',
            unique_together={('user', 'resource')},
        ),
    ]
