# Generated by Django 5.2 on 2026-03-05 08:57

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='resource_search_gin'),
        ),
    ]
