# Generated by Django 5.2 on 2026-03-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='resource',
            name='cover_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='resources/covers/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='btn_text',
            field=models.CharField(default='Explore Now', help_text='Button label.', max_length=50),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide from homepage.'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='link',
            field=models.CharField(default='/library', help_text='Where the CTA button links to.', max_length=200),
        ),
    ]
