# Generated by Django 5.2 on 2026-03-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_search_vector_resource_resource_search_gin'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main headline for the slide.', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Subtext below the headline.', max_length=300)),
                ('image', models.ImageField(help_text='High-resolution background image.', upload_to='hero_slides/')),
                ('link', models.CharField(default='/library', help_text='Where the button should go (e.g., /library or /products/1).', max_length=200)),
                ('btn_text', models.CharField(default='Explore Now', help_text='Text inside the button.', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this slide from the homepage.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['display_order'],
            },
        ),
    ]
