# Generated by Django 5.2 on 2026-03-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Check this box to showcase this resource on the homepage.'),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Check this box if this resource is free to download without a premium subscription.'),
        ),
    ]
